=== masonmcelvain/csc-366-project/xml/employees.dtd
<!ELEMENT employees (employee)+>
<!ELEMENT employee (firstName, lastName, startDate, endDate, paycheck*)>
<!ATTLIST employee 
    empId ID #REQUIRED
    managedBy IDREF #IMPLIED
>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>
<!ELEMENT paycheck EMPTY>
<!ATTLIST paycheck 
    id ID #REQUIRED
    rate CDATA #REQUIRED
    hours CDATA #REQUIRED
    taxes CDATA #REQUIRED
    sickHoursAccrued CDATA #REQUIRED
    overtimeHours CDATA #REQUIRED
    netPay CDATA #REQUIRED
    sickHoursUsed CDATA #REQUIRED
>

=== masonmcelvain/csc-366-project/xml/employees.xml
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees>
    <employee empId="e1">
        <firstName>John</firstName>
        <lastName>Smith</lastName>
        <startDate>01/02/1998</startDate>
        <endDate>06/12/2020</endDate>
        <paycheck id="p1" rate="15.00" hours="20" taxes="31.34" sickHoursAccrued="8" overtimeHours="0" netPay="268.66" sickHoursUsed="0" />
    </employee>
    <employee empId="e2">
        <firstName>John</firstName>
        <lastName>Smith</lastName>
        <startDate>01/02/1998</startDate>
        <endDate>06/12/2020</endDate>
    </employee>
</employees>
