=== masonmcelvain/csc-366-project/xml/order.dtd
<!ELEMENT Orders (Order*)>
<!ELEMENT Order (Tax, Subtotal, Total, Date, Customer, LineItem+)>
<!ATTLIST Order order_id ID #REQUIRED>
<!ATTLIST Order location_id CDATA #REQUIRED>
<!ELEMENT Tax (#PCDATA)>
<!ELEMENT Subtotal (#PCDATA)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Date (#PCDATA)>

<!ELEMENT Customer (FirstName, LastName)>
<!ATTLIST Customer customer_id ID #REQUIRED>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>

<!ELEMENT LineItem (Product, Quantity, Subtotal, Tax)>
<!ATTLIST LineItem line_item_id ID #REQUIRED>
<!ELEMENT Quantity (#PCDATA)>

<!ELEMENT Product (ProductName, Price, (Packaged|Prepared))>
<!ATTLIST Product sku ID #REQUIRED>
<!ELEMENT ProductName (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

<!ELEMENT Packaged (Size)>
<!ELEMENT Size (#PCDATA)>

<!ELEMENT Prepared (Recipe)>
<!ELEMENT Recipe (Ingredient+)>
<!ELEMENT Ingredient (IngredientName)>
<!ATTLIST Ingredient ingredient_id ID #REQUIRED>
<!ELEMENT IngredientName (#PCDATA)>

=== masonmcelvain/csc-366-project/xml/order.xml
<!DOCTYPE Orders SYSTEM "order.dtd">
<Orders>
  <Order order_id="order_1" location_id="l1">
    <Tax>1.50</Tax>
    <Subtotal>50.00</Subtotal>
    <Total>55.50</Total>
    <Date>2007-01-01</Date>
    <Customer customer_id="customer_1">
      <FirstName>John</FirstName>
      <LastName>Doe</LastName>
    </Customer>
    <LineItem line_item_id="line_item_1">
      <Product sku="sku_1">
        <ProductName>Product 1</ProductName>
        <Price>10.00</Price>
        <Packaged>
          <Size>Small</Size>
        </Packaged>
      </Product>
      <Quantity>1</Quantity>
      <Subtotal>10.00</Subtotal>
      <Tax>0.50</Tax>
    </LineItem>
    <LineItem line_item_id="line_item_2">
      <Product sku="sku_2">
        <ProductName>Product 2</ProductName>
        <Price>20.00</Price>
        <Prepared>
          <Recipe>
            <Ingredient ingredient_id="ingredient_1">
              <IngredientName>Ingredient 1</IngredientName>
            </Ingredient>
            <Ingredient ingredient_id="ingredient_2">
              <IngredientName>Ingredient 2</IngredientName>
            </Ingredient>
          </Recipe>
        </Prepared>
      </Product>
      <Quantity>2</Quantity>
      <Subtotal>40.00</Subtotal>
      <Tax>1.00</Tax>
    </LineItem>
  </Order>
</Orders>
